#pragma once

#define ANIMATION_MARIO_IDLE  102
#define ANIMATION_MARIO_IDLE_LEFT  101
#define ANIMATION_MARIO_IDLE_RIGHT 102
#define ANIMATION_MARIO_FACE_LEFT  103
#define ANIMATION_MARIO_FACE_RIGHT 104